# Generated by Django 4.2.7 on 2025-11-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('current_job_title', models.CharField(blank=True, max_length=200)),
                ('years_of_experience', models.CharField(blank=True, max_length=50)),
                ('expected_salary', models.CharField(blank=True, max_length=100)),
                ('notice_period', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('how_did_you_hear', models.CharField(blank=True, max_length=100)),
                ('available_start_date', models.DateField(blank=True, null=True)),
                ('willing_to_relocate', models.CharField(blank=True, max_length=10)),
                ('requires_sponsorship', models.CharField(blank=True, max_length=10)),
                ('cover_letter_text', models.TextField(blank=True)),
                ('cover_letter_file', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
